- name: Validate support for distribution
  fail: msg="For yum based package managers, only 'CentOS', 'Fedora', 'OpenSuse', 'RedHat' are supported."
  when: ansible_distribution not in ['CentOS', 'Fedora', 'OpenSuse', 'RedHat'] or ansible_distribution_major_version|int < 6 or ansible_distribution_major_version|int > 7

- name: RHEL 6 install dependencies
  yum: >
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
    - unzip
    - "https://dl.fedoraproject.org/pub/epel/6/x86_64/jq-1.3-2.el6.x86_64.rpm"
  when: ansible_distribution in ['CentOS', 'Fedora', 'OpenSuse', 'RedHat'] and ansible_distribution_major_version|int == 6

- name: RHEL 7 install dependencies
  yum: >
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
    - unzip
    - "https://dl.fedoraproject.org/pub/epel/7/x86_64/j/jq-1.3-2.el7.x86_64.rpm"
  when: ansible_distribution in ['CentOS', 'Fedora', 'OpenSuse', 'RedHat'] and ansible_distribution_major_version|int == 7
